version: "3.9"

services:
  frontend:
    build:
      context: .
    container_name: frontend-next
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_HOST: "http://localhost"
      NEXT_PUBLIC_BACKEND_PORT: "9999"

networks:
  default:
    driver: bridge
