version: '3.8'

services:
  api01: &api
    build:
      context: .
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - POSTGRES_DB=contactsdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - POSTGRES_DB=contactsdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    hostname: ngnix
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: contactsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

networks:
  default:
    driver: bridge
    name: nginx

volumes:
  postgres_data: