spring:
  application:
    name: backend
  r2dbc:
    url: r2dbc:postgresql://${DB_HOSTNAME:localhost}:5432/${POSTGRES_DB:contactsdb}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:123456}
    jpa:
      hibernate:
        ddl-auto: none
    sql:
      init:
        mode: always